[package]
name    = "mongo_driver"
version = "0.1.0"
authors = ["Thijs Cadier <thijs@appsignal.com>"]

[dependencies]
libc = "*"
bson = "*"

[dependencies.mongo_c_driver_wrapper]
path = "mongo_c_driver_wrapper"
