[package]
name        = "mongo_driver"
version     = "0.1.0"
authors     = ["Thijs Cadier <thijs@appsignal.com>"]
description = "Mongo Rust driver built on top of the Mongo C driver"
readme      = "README.md"
repository  = "https://github.com/thijsc/mongo-rust-driver"
keywords    = ["mongodb", "database"]
license     = "MIT/Apache-2.0"

[[test]]
name = "tests"

[dependencies]
libc = "> 0.2.0"
log  = "> 0.3.0"
bson = "> 0.1.0"

[dependencies.mongoc-sys]
path    = "mongoc-sys"
version = "1.3.0"

[dev-dependencies]
chrono = "*"
