[package]
name          = "mongo_driver"
version       = "0.7.1"
authors       = ["Thijs Cadier <thijs@appsignal.com>"]
description   = "Mongo Rust driver built on top of the Mongo C driver"
readme        = "README.md"
documentation = "https://docs.rs/mongo_driver/"
repository    = "https://github.com/thijsc/mongo-rust-driver"
keywords      = ["mongodb", "database"]
license       = "MIT/Apache-2.0"

[[test]]
name = "tests"

[dependencies]
libc = "0.2"
log  = "0.3"
bson = "0.8"

[dependencies.mongoc-sys]
path    = "mongoc-sys"
version = "1.6.3"

[dev-dependencies]
chrono = "> 0.2.0"
