[package]
name    = "mongo_c_driver_wrapper"
version = "1.1.10"
build   = "build.rs"
authors = ["Thijs Cadier <thijs@appsignal.com>"]

[dependencies]
libc       = "*"

[build-dependencies]
pkg-config = "*"

[build-dependencies.bindgen]
git = "https://github.com/crabtw/rust-bindgen.git"
